# name: CI/CD Pipeline

# on:
#   push:
#     branches:
#       - main
#   pull_request:
#     branches:
#       - main

# jobs:
#   build:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout repository
#         uses: actions/checkout@v2

#       - name: Set up Node.js
#         uses: actions/setup-node@v2
#         with:
#           node-version: "14"

#       - name: Install dependencies
#         run: yarn install

#       - name: Lint code
#         run: yarn lint

#       - name: Run tests
#         run: yarn test

#       - name: Build application
#         run: yarn build

#       - name: Upload production-ready build files
#         uses: actions/upload-artifact@v2
#         with:
#           name: build-files
#           path: dist

#   deploy:
#     runs-on: ubuntu-latest
#     needs: build
#     if: github.ref == 'refs/heads/main'

#     steps:
#       - name: Download build files
#         uses: actions/download-artifact@v2
#         with:
#           name: build-files
#           path: dist

#       - name: Deploy to server
#         uses: easingthemes/ssh-deploy@v2.0.7
#         env:
#           SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
#           ARGS: "-rltgoDzvO --delete"
#           SOURCE: "dist/"
#           REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
#           REMOTE_USER: ${{ secrets.REMOTE_USER }}
#           TARGET: ${{ secrets.REMOTE_TARGET }}
